--- 

# Tell Travis we don't use sudo so that we can use container infrastructure
# for the builds.
sudo: false

# We're currently only using Travis CI for automatic Forge deployment. No real
# test is run. This is specified here in order to override the default test.
script: /bin/true

deploy:
  provider: puppetforge
  user: tse
  password:
    secure: "I3wvohnETO/Vj0XinvWzkN/Pzv40CSh09/R+x4yKYywFib+eFpBSNllHwAZkCV/ECyd4xjJDWyg7PBFov3vzY4P6dtngliuP4dqDpyXBHr1uSmO3HEkj9xO07u8oti1LMhul9glFW6Q1yZzwJhe2fDF0ePDUK9MRMSYmTBVDcVVx7QbpdwaxN1icitnywT4cW26k4KFWuCr4lfg71KBP6vV/gZQbQeTpXwGpgOiS/DnoYT0oXAQRSYoeO6EOj2XAyEvT2EHHHnHbbXArc0G/4+waVi94rZNSYLJmZB7AsukAKd0ElijShfzqCI7jyftYJR2d/Zc5eAhpdanjeVYchuHeYPtBQPDiUP5V/J0HSSAQ6pQPKdJwX2C1DMeYcFKOEoWiMOwfCW+QR9y40PL8mF/C8y+nI/KwM8zgwc/ri65+mQB9cReY7Nd3zcDNHBqWRyGEdOGqvN8nmMY8XmMtS/eaeZQnzncvEvFNDSrxEjEke6JI8Ige9rtQUXcJPWJIePO+KVaMXi4tP2BUY5WnnCGMRDuE+JQbYGdoqkf96c7W98EfCgO2KGJCXAWY+Pr5g0Dr98XiUdUk1D+1J27k4Jb5yY9hshW/lmBqwldJd+PGSPA9CJYE8+vVmq0CZyNrw0XQM/W+OY3uebLjcs9795vJIRwNiFsMnSij0sp4o2Y="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
